### PR TITLE
Qt GUI: first draft

### PR DESCRIPTION
**Pull request by olear**
Hi, included is first draft of the Qt GUI. May still need some adjustments.
untitled

Build and install project (includes the bash script):

```
qmake && make install
```

or

```
qmake && make
./build/audio2ascii-qt
```

Please test and give feedback.

### CODE REVIEW

**Comment by rcspam** [comment]
Good job, thanks you to refer to me (a non Qt devel ;)

**Comment by olear** [comment]
Qt is easy, open the pro file in qtcreator and see for yourself :)

Will do some more adjustments to the gui. Dimensions selection should probably be x, y, x+y ? instead of 1 and 2?

**Comment by rcspam** [comment]
1. Have no time to learn it ! :(
2. Yes i agree.
   I'm happy to see that you use directly the sox library to convert. Very good thing !
   Is it possible to directly use it in open-arena ? So a button to generate curve (like in nuke) could be add directly without do that through audio2ascii ?

**Comment by olear** [comment]
I just use the sox binary the same way you use it in Bash. When everything is working 100%, and when I get the time I can move to libsox, and then later port to a OpenFX plugin (in openfx-arena).

**Comment by rcspam** [comment]
I have test. I adore the refresh button to let max amount curve around 1.

**Comment by rcspam** [comment]
I wanted to add a advised mult. factor in order to have the curve between 0 and 1 with a pre-analyse of the data.  What do you think?

**Comment by olear** [comment]
Just give me specs/info, or add to bash script and I will adapt :) Need to go to work, but will be available later today, have a nice day

**Comment by rcspam** [comment]
Need to go to work as well, i'll try late today.
Have a nice day

**Comment by olear** [comment]
Updated the gui
a2a

**Comment by rcspam** [comment]
Update with deviation max info and restart button

https://github.com/rcspam/audio2ascii/releases/tag/0.5

**Comment by rcspam** [comment]
If i have time i'll try to add a deviation max parameter to scale the curve as wanted. (is it good english ? I dont know;)

**Comment by rcspam** [comment]
I have test qt-version.Can you add other format support (mp3 ...) by sox in the file selector...
To do that on command line i has needed to add libsox-fmt package on ubuntu.
It's so cool take an audio without have to convert ;)

**Comment by olear** [comment]
Can add a function that ask sox for supported formats and updates the filedialog based on that.

**Comment by olear** [comment]
Windows build: https://github.com/olear/audio2ascii/releases/tag/win32-preview
untitled

**Comment by rcspam** [comment]
Have you test import our curve in natron, render and mix with audio file?
Is the sync ok ?

**Comment by olear** [comment]
Been doing minimal testing in Natron, need to test more :)

**Comment by rcspam** [comment]
Just quick add with your idea to display out file with in head the max variation info, before recompute if needed...
https://github.com/rcspam/audio2ascii/releases/tag/0.6

**Comment by rcspam** [comment]
I have replace Mult. Factor by a adjustment in x and in y (in pixels) of the waveform:
This allows an easiest way to setup the waveform on the canvas.
After several test in Natron/Nuke it seems to work well.
What do you think?
PS: i really sorry to have revert the pull request, bad knowledge of git command line.
I'm a very beginner with git ;)

**Comment by rcspam** [comment]
Here is the final version: https://github.com/rcspam/audio2ascii/releases/tag/1.0

**Comment by olear** [comment]
will adjust to your changes and do a new pull request.

**Comment by olear** [comment]
Quick (and possible stupid) awk question, what does the awkmax function do?

**Comment by rcspam** [comment]
I have separate awkmax from the other for lightening awkx & awky, it was more clear for me. But it was not  mandatory.  It just calculate the variation max in the brut .dat file produce by sox to give this info to user. One awk parser might well have been enough. The fun part is, i did it for your speedest understanding ;)).

**Comment by olear** [comment]
I'm no big user of awk :) (I mainly use it for word extraction).

**Comment by rcspam** [comment]
I sympathize :)
I'm sure you know more on c++/qt than me on awk.
I just code some bash scripts for my own use, that's all that i know and a little of sed/awk.

**Comment by rcspam** [comment]
Hi olear,

No time to progress with qt-version ... and a new pull request? ;)
Cheers

**Comment by olear** [comment]
Busy, will look at it tonight if I get the time, feel free to test my fork.

**Comment by rcspam** [comment]
Updated to [release 1.2](https://github.com/rcspam/audio2ascii/releases/tag/v1.2)

**Comment by olear** [comment]
Hi, got some free time later today, what needs to be done on the qt side?

https://github.com/olear/audio2ascii/blob/master/qt/sox.cpp#L104
This is how I currently calc the stuff.

**Comment by rcspam** [comment]
Hi,
If i understand (if i figure out, in my case;)) your code.
You multiply both inputs  by the factor in x or/and in y, as in the firsts release of audio2ascii
Right?
As [i wrote above](https://github.com/rcspam/audio2ascii/pull/2#issuecomment-115285559), I have replace "Mult. Factor" by a adjustment in x and in y (in pixels) of the waveform.
This allows an easiest way to setup the waveform on the canvas.
I have change "factor" in a value in pixels. 

E.g.:  A canvas of 2000x1000, an image of 500x500 in the center, want this image move without exit of the canvas. So we must set x value  to a maximum of 750 and y to a maximum of 250. So the image stay in the canvas.Easy!

After several tests, it's an better way to do. We just set the number of pixels we want. 
Thats why i must parse the .dat a first time (awkmax), ho ! i understand now you question above;), to know the max variation **maxd{x,y}** before calculate the new scale curve: **(${2,3}*fact{x,y}/maxd{x,y})** in the other awk scripts. That's the rationale for "awkmax".

**Comment by olear** [comment]
Thanks for the info, will adapt.

**Comment by rcspam** [comment]
Hi olear,
As you know, i'm a great c++/qt dev;) ! That's why i ask you, if you can and have some minutes to code a simple node with a file path to fill (with the path to an executable) and a simple button to launch this executable. So we can launch audio2curve from Natron....
Mockup:
mockup

I hope this is a possible stuff
Thanx

**Comment by olear** [comment]
If you want more integration with Natron, then a proper Read node should be made (on my TODO list), or maybe you can script what you want in Python.

**Comment by rcspam** [comment]
I'll try but, i am not a expert !
cu

**Comment by rcspam** [comment]
Done ;) 
Thanks to @MrKepzie to his [help](https://groups.google.com/forum/?hl=en#!topic/natron-vfx/D-5fTn4iM7M)
https://github.com/rcspam/audio2ascii/releases/tag/v1.3

**Comment by rcspam** [comment]
With the new [version 1.4](https://github.com/rcspam/audio2ascii/releases/tag/v1.4) of the plugins/script. We can now generate curve directly in Natron to link it to what we want animate.

screenshot

**Comment by olear** [comment]
Great :)

Sorry for lack of work on my part.

Next step would be to drop the shell script and do everything in Python ;)

**Comment by rcspam** [comment]
Yes i know, it could be cool  for other platform than _nix and this could be coded directly in the plugin.
I have yet try with *_pysox*\* but it has a bug which is impossible to write output at the right rate (always stay at 44100hz - it's too much if i want 24/25 hz ;),  no matter the rate we pass in the input and its development is stop since 2011 :(  so  i'll try to find a replacement. But i have very little time right now (1/2 or 1 hour around out there in the week) and as you know, i'm a beginner with python code...
The next step is to put the gui interface in the Node and add some improvements (range frame, launch external app to edit the audio file -audacity could be well-).
I don't know if natron caches are available from the  'python natron interface', but perhaps add a preview by combining cache and ffmpeg, i don't know if its possible, what you think ?!

**Comment by rcspam** [comment]
With the [version 1.5](https://github.com/rcspam/audio2ascii/releases/tag/v1.5) ... no more gui... Directly set parameters in Natron ;)
But  always need the script bash !

screenshot1

screenshot2

**Comment by olear** [comment]
I'm scrapping my qt port, and will rather help port the shell script to python etc.

**Comment by rcspam** [comment]
I think an little soft in command line in c/c++. I really don't know them. But you begin to understand libsox. 
Bash script is not portable to windows. So, i think you can do that when it's possble. What you think ?

**Comment by rcspam** [comment]
You think speeder that i write ;)) !!

**Comment by olear** [comment]
Ignore libsox and use the sox binary, just as in the shell script and my qt port.
- Add a new param for path to sox
- check for sox binary
- check for audio file
- check for tmp path (use one provided by python, that will ensure compat on win/mac)
- run the sox command
- etc .....

**Comment by rcspam** [comment]
Impossible to port with pysox, sox users on mailing list have confirm that we can't change the rate of the output file with it. A python sox lib named [xbob.sox](https://github.com/bioidiap/xbob.sox) could make the job but the depends not simple to install for end users !

**Comment by olear** [comment]
Use the sox binary directly as in your shell script with os.system.

**Comment by rcspam** [comment]
I think i'll add a file path and a button to launch an external app. that the user can set e.g; audacity to retouch the file ..... If it's possible to read the cache frome python plugins, i dont yet, in the spirit that audio2ascii, we can do some a ffplay/mplayer or something like that to read cache sync with audiofile....

**Comment by rcspam** [comment]
[New version](https://github.com/rcspam/audio2ascii/releases/tag/v1.6) with possibility to call an external audio editor

**Comment by rcspam** [comment]
[Version 1.8](https://github.com/rcspam/audio2ascii/releases/tag/v1.8) is out.
Now Linux user can preview audio sync with Viewer.
[Here is a demo](https://www.youtube.com/watch?v=koagSOPnsVw)

**Comment by rcspam** [comment]
[Version 1.9](https://github.com/rcspam/audio2ascii/releases/tag/v1.9): I hope OSX users can play with it (really i hope, i have no Mac)

**Comment by MrKepzie** [comment]
Tested:

It loads but:
- I get this error
  Failed to execute callback: Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/alexandre/NatronProjects/AudioToAscii.py", line 138, in paramHasChanged
  if thisParam == thisNode.playSync:
  AttributeError: 'NatronEngine.Effect' object has no attribute 'playSync'

Obviously this is because the “playSync” param is defined only when on Linux ( See line 469 if NatronEngine.natron.isLinux():)
- Why not use an environment variable for the audio2ascii.sh script ? Or even use the Natron path ? adding it to the Path is cumbersome. 
- I had to modify in audio2ascii.sh

if [[! which sox >/dev/null]];then
    echo "$0 require 'sox' which is not installed"
    exit 1  
fi
Otherwise it would always error even with sox in path.
-  I had to chmod audio2ascii.sh otherwise I would get a “permission denied” when clicking “Generate curve”

After these fixes, it works great.

**Comment by rcspam** [comment]
Oops ! "isLinux", bad ctrl-Z ;) I'll fix that.
I didn't know we can put an executable directly in Natron plugin path. So it's a good news.
Is the ffplay preview (sad solution, i know) works too?

**Comment by olear** [comment]
Don't like this https://github.com/rcspam/audio2ascii/blob/master/AudioToAscii.py#L157 & https://github.com/rcspam/audio2ascii/blob/master/AudioToAscii.py#L141

That should be handled better.

I can put the ffplay stuff in the audiocurve cli app, and maybe add a cmdline switch to "kill" the playback(?). That way the pyscript only has to deal with one binary (the audiocurve cli will then handle sox/ffmpeg and is cross-platform).

example:
play audio: audiocurve -input audio.wav -playback duration
stop audio: audiocurve -noplay

or something ...

**Comment by rcspam** [comment]
I know it's "sad/bad" to kill an app this way the goal for now was to test audio2ascii.sh on the Osx bash version.If i'm right, OSX use freeBSD-based bash 3.2.\* which have few small differences compare to linux bash 4.\* versions.
Put a pid number in a tmp file could be another simple way.

**Comment by olear** [comment]
btw, sox also does playback, any reason for using ffplay vs. sox?

**Comment by rcspam** [comment]
If i have read man page correctly, you must give a number of repeat , no infinite loop the audio.
e.g.: sox some.wav trim 0 2 repeat 3.
Can you confirm if i'm right ?

**Comment by olear** [comment]
Yes, you are right (i though maybe repeat 0 would work). Then ffplay is good enough.

**Comment by rcspam** [comment]
@MrKepzie, I have made test on Mountain Lion via Virtualbox.(Pfff !)
I have change '_if [[! which sox >/dev/null]]_' by '_if [[ ! $(which sox >/dev/null) ]]_' in order to bash works on both Linux and Osx.
Audio2ascci  works well on Osx if i start Natron from terminal. However it's not the case from the desktop. So, are you some ideas how to declare the Path variables for unix command or  command-line app ?
The only bash config file is sufficient on Linux !

**Comment by MrKepzie** [comment]
A more flexible approach should be to put your audio2ascii.sh script right next to the PyPlug, and in your Pyplug you would need to look for audio2ascii.sh in all locations of the Natron search paths.

**Comment by rcspam** [comment]
It is always in the PyPlug Dir (line 43-46 in AudioToAscii.py), i 'm talking about commandline app sox ffplay.

**Comment by rcspam** [comment]
I really sorry to misunderstand where put the bash script. In the PyPlug Path ?

**Comment by rcspam** [comment]
OSX user can now install [version 2beta](https://github.com/rcspam/audio2ascii/releases/tag/v2.0beta) simply. Just copy files in home natron plugins directory.
@MrKepzie  A environement variables for  home natron plugins directory could be cool ;)

sc

**Pull request merged**
